name: anihelp_admin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  modal_progress_hud: ^0.1.3
  lottie: ^1.0.1
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  firebase_storage:
  google_nav_bar: ^5.0.5
  better_player: ^0.0.68
  cached_network_image: ^3.0.0
  image_picker: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: CarterOne
      fonts:
        - asset: fonts/CarterOne-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

  assets:
    - assets/